NewsNow/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using NewsNow.Models;
using ML;
using Microsoft.AspNetCore.Authorization;

namespace NewsNow.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly NewsNowContext _context;
        private readonly IHostingEnvironment _env;

        private readonly string _articlesTransitionDataPath;

        public ArticlesController(NewsNowContext context, IHostingEnvironment env)
        {
            _context = context;
            _env = env;

            // If working in Visual Studio, make sure the 'Copy to Output Directory'
            // property of the file is set to 'Copy always'
            _articlesTransitionDataPath = System.IO.Path.Combine(_env.WebRootPath, "ml", "articles-transition-data.txt");
        }

        [Authorize]
        // GET: Articles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Articles.ToListAsync());
        }

        // GET: Articles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles.Include(a => a.Category).FirstOrDefaultAsync(m => m.ArticleId == id);

            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        public async Task<IActionResult> MoveRelated(int? prevId, int? newId)
        {
            if (prevId == null || newId == null)
            {
                return NotFound();
            }
            
            string line = ((float) prevId).ToString("0.0") + ',' + ((float) newId).ToString("0.0");
            System.IO.File.AppendAllText(_articlesTransitionDataPath, line + Environment.NewLine);

            return RedirectToAction(nameof(Details), new {id = newId });
        }

        public async Task<IActionResult> Comments(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comments = await _context.Comments.Where(c => c.ArticleId == id.Value).ToListAsync();

            if (comments == null)
            {
                return NotFound();
            }

            return Json(comments);
        }

        public async Task<IActionResult> Search(int? category, string header, string summery, DateTime? date)
        {
            var result = _context.Articles.AsQueryable();

            if (category != null)
                result = result.Where(x => x.CategoryId == category);
            if (!String.IsNullOrWhiteSpace(header))
                result = result.Where(x => x.Header.Contains(header));
            if (!String.IsNullOrWhiteSpace(summery))
                result = result.Where(x => x.Summery.Contains(summery));
            if (date.HasValue)
                result = result.Where(x => x.DateCreated.Value.Date == date.Value.Date);

            return Json(result);
        }

        public async Task<IActionResult> GetRelatedArticles(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            const int NUM_OF_RELATED_ARTICLES = 3;
            var relatedArticles = new List<Article>();

            try
            {
                int mlRelatedArticle = MachineLearning.GetRelatedArticle(_articlesTransitionDataPath, id.Value);

                if (mlRelatedArticle != id.Value)
                {
                    var article = await _context.Articles.FirstAsync(c => c.ArticleId == mlRelatedArticle);

                    if (article != null)
                    {
                        relatedArticles.Add(article);

                        // Try to find a related article to the related article
                        int mlRelatedToRelatedArticle = MachineLearning.GetRelatedArticle(_articlesTransitionDataPath, mlRelatedArticle);

                        if (mlRelatedToRelatedArticle != mlRelatedArticle && mlRelatedToRelatedArticle != id.Value)
                        {
                            article = await _context.Articles.FirstAsync(c => c.ArticleId == mlRelatedToRelatedArticle);

                            if (article != null)
                            {
                                relatedArticles.Add(article);
                            }
                        }
                    }
                }

            }
            catch (Exception)
            {
                // It's just mean that there is no data yet for this article
            }

            int articlesCount = _context.Articles.Count();
            Random random = new Random();

            // Fill the rest of the related articles with random articles, in order to
            // have the option for diversity (and by that make better predictions in the future)
            while (relatedArticles.Count() < NUM_OF_RELATED_ARTICLES)
            {
                int randomArticleId = random.Next(1, articlesCount);

                if (randomArticleId != id.Value && !relatedArticles.Exists(c => c.ArticleId == randomArticleId))
                {
                    var randomArticle = await _context.Articles.FirstAsync(c => c.ArticleId == randomArticleId);

                    if (randomArticle != null)
                    {
                        relatedArticles.Add(randomArticle);
                    }
                }
            }

            return Json(relatedArticles);
        }

        // GET: Articles/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(_context.Categories, "CategoryId", "Name");
            return View();
        }

        // POST: Articles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Header,Summery,Content,HomeImageUrl,CategoryId,Location,IsShowMap")] Article articleModel)
        {
            if (ModelState.IsValid)
            {
                articleModel.DateCreated = DateTime.Now;
                _context.Add(articleModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(articleModel);
        }

        // GET: Articles/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles.FindAsync(id);
            if (article == null)
            {
                return NotFound();
            }

            ViewBag.Categories = new SelectList(_context.Categories, "CategoryId", "Name");

            return View(article);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("ArticleId,Header,Summery,Content,HomeImageUrl,CategoryId,Location,IsShowMap")] Article article)
        {
            if (id != article.ArticleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Articles.Attach(article);
                    _context.Entry(article).Property(x => x.Content).IsModified = true;
                    _context.Entry(article).Property(x => x.Header).IsModified = true;
                    _context.Entry(article).Property(x => x.Summery).IsModified = true;
                    _context.Entry(article).Property(x => x.HomeImageUrl).IsModified = true;
                    _context.Entry(article).Property(x => x.CategoryId).IsModified = true;
                    _context.Entry(article).Property(x => x.Location).IsModified = true;
                    _context.Entry(article).Property(x => x.IsShowMap).IsModified = true;

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticleExists(article.ArticleId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(article);
        }

        // GET: Articles/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles
                .FirstOrDefaultAsync(m => m.ArticleId == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // POST: Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var article = await _context.Articles.FindAsync(id);
            _context.Articles.Remove(article);
            await _context.SaveChangesAsync();

NewsNow/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NewsNow.Models;

namespace NewsNow.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly NewsNowContext _context;

        public CategoriesController(NewsNowContext context)
        {
            _context = context;
        }

        // GET: Categories
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewData["Articles"] = await _context.Articles
                .Where(x => x.CategoryId == id).ToListAsync();

            if (id == null)
            {
                return NotFound();
            }

            var categoryModel = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (categoryModel == null)
            {
                return NotFound();
            }

            return View(categoryModel);
        }

        [Authorize]
        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("CategoryId, Name, Description, Color")] Category categoryModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(categoryModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(categoryModel);
        }

        // GET: Categories/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoryModel = await _context.Categories.FindAsync(id);
            if (categoryModel == null)
            {
                return NotFound();
            }
            return View(categoryModel);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId, Name, Description, Color")] Category categoryModel)
        {
            if (id != categoryModel.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoryModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryModelExists(categoryModel.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoryModel);
        }

        // GET: Categories/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoryModel = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (categoryModel == null)
            {
                return NotFound();
            }

            return View(categoryModel);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Remove articles of the selected category
            foreach (Article article in _context.Articles.Where(article => article.CategoryId == id))
            {
                _context.Articles.Remove(article);
            }

            var categoryModel = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(categoryModel);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryModelExists(int id)
        {
            return _context.Categories.Any(e => e.CategoryId == id);
        }
    }
}

NewsNow/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NewsNow.Models;

namespace NewsNow.Controllers
{
    public class SearchController : Controller
    {
        private readonly NewsNowContext _context;

        public SearchController(NewsNowContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Categories = _context.Categories.ToList<Category>();
            return View();
        }
    }
}

NewsNow/Views/Shared/_ArticleHorizontal.cshtml
@model NewsNow.Models.Article

<div class="card flex-md-row mb-4 shadow-sm h-md-250">
    <div class="card-body d-flex flex-column align-items-start" style="background-color: #f2eeee;">
        <partial name="_CategoryBadge" model="@Model.Category" />
        <h3 class="mb-0">
            <a class="text-dark" asp-controller="Articles" asp-action="Details" asp-route-id="@Model.ArticleId">@Html.DisplayFor(model => model.Header)</a>
        </h3>
        <div class="mb-1 text-muted">@Html.DisplayFor(model => model.DateCreated)</div>
        <p class="card-text mb-auto">@Html.DisplayFor(model => model.Summery)</p>
        <a class="btn btn-sm btn-outline-secondary" asp-controller="Articles" asp-action="Details" asp-route-id="@Model.ArticleId">Read more...</a>
    </div>
    <a asp-controller="Articles" asp-action="Details" asp-route-id="@Model.ArticleId" class="bg-dark">
        <img class="card-img-right flex-auto d-none d-lg-block" style="width: 400px; height: 250px;" src="@Html.DisplayFor(model => model.HomeImageUrl)">
    </a>
</div>

NewsNow/Views/Shared/_ArticleVertical.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@model NewsNow.Models.Article

<div class="card" style="width: 18rem; background-color: #f2eeee">
    <a asp-controller="Articles" asp-action="Details" asp-route-id="@Model.ArticleId">
        <img data-toggle="tooltip"
             data-html="true"
             data-placement="bottom"
             title="@Html.DisplayFor(model => model.Summery)"
             class="card-img-top"
             data-src="holder.js/100px180/"
             alt="100%x180"
             style="height: 180px; width: 100%; display: block;"
             src="@Html.DisplayFor(model => model.HomeImageUrl)"
             data-holder-rendered="true">
    </a>
    <div class="card-body">
        <h5 class="card-title">@Html.DisplayFor(model => model.Header)</h5>
        <!--<p class="card-text">@Html.DisplayFor(model => model.Summery)</p>-->
        <a class="btn btn-sm btn-outline-secondary" asp-controller="Articles" asp-action="Details" asp-route-id="@Model.ArticleId">Read more...</a>
    </div>
</div>

NewsNow/Views/Shared/_CategoryBadge.cshtml
@model NewsNow.Models.Category

<a asp-controller="Categories" asp-action="Details" asp-route-id="@Model.CategoryId">
    <span class="badge badge-secondary" style="background-color: @Model.HexColor">@Html.DisplayFor(model => model.Name)</span>
</a>

NewsNow/Views/Shared/_HeaderPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using NewsNow.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<header class="blog-header border shadow-sm">
    <div class="container">
        <div class="d-flex justify-content-between">
            <div class="p-2">
                @if (SignInManager.IsSignedIn(User))
                {
                <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="btn-group btn-group-justified" role="group">
                    <button type="submit" class="btn btn-outline-secondary">Log out</button>
                    <a asp-controller="Statistics" asp-action="Index" class="btn btn-outline-secondary">Statistics</a>
                    <a asp-controller="Categories" asp-action="Index" class="btn btn-outline-secondary">Categories</a>
                    <a asp-controller="Articles" asp-action="Index" class="btn btn-outline-secondary">Articles</a>
                </form>
                }
                else
                {
                    <a class="btn btn-sm btn-outline-secondary" asp-area="" asp-controller="Account" asp-action="Login">Log in</a>
                }
            </div>
            <div class="p-2 bd-highlight">
                <a class="blog-header-logo text-dark" href="@Url.Action("Index", "Home")">
                    <img src="~/images/NewsNowLogoBlack_300x65.png.png" class="animate-logo" />
                </a>
                <br />
            </div>
            <div class="p-2 bd-highlight">

                <a class="text-muted" href="@Url.Action("Index", "Search")" style="vertical-align: super;">
                    <svg xmlns="http://www.w3.org/2000/svg" style="vertical-align: sub;" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3">
                        <circle cx="10.5" cy="10.5" r="7.5"></circle>
                        <line x1="21" y1="21" x2="15.8" y2="15.8"></line>
                    </svg>
                </a>

                @if (SignInManager.IsSignedIn(User))
                {
                    <span class="badge badge-danger">WARNING: ADMIN MODE</span>
                }
                else
                {
                    <a href="https://twitter.com/mideastbeasties?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-size="large" data-show-screen-name="false" data-dnt="true" data-show-count="false">Follow Us</a>
                    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                }
            </div>
        </div>
    </div>
</header>

NewsNow/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NewsNow</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/simplemde/dist/simplemde.min.css" />
        <link rel="stylesheet" href="~/fonts/Alef/Alef.css">
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/articles.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/articles.min.css"/>
    </environment>
</head>
<body>
    @Html.Partial("_HeaderPartial")
    <div class="container">
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p class="footer-style">&copy; 2018 - NewsNow</p>
            </footer>
        </div>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-tmpl/jquery.tmpl.js"></script>
        <script src="~/js/twitter.js"></script>
        <script src="~/lib/popper/popper.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
        <script src="~/lib/showdown/dist/showdown.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/markdown.js"></script>
        <script src="~/lib/simplemde/dist/simplemde.min.js"></script>
        <script src="~/lib/fitty-gh-pages/dist/fitty.min.js"></script>
        <script src="~/js/api.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {
            $(".animate-logo").height(30);
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>