NewsNow/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using NewsNow.Models;
using ML;
using Microsoft.AspNetCore.Authorization;

namespace NewsNow.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly NewsNowContext _context;
        private readonly IHostingEnvironment _env;

        private readonly string _articlesTransitionDataPath;

        public ArticlesController(NewsNowContext context, IHostingEnvironment env)
        {
            _context = context;
            _env = env;

            // If working in Visual Studio, make sure the 'Copy to Output Directory'
            // property of the file is set to 'Copy always'
            _articlesTransitionDataPath = System.IO.Path.Combine(_env.WebRootPath, "ml", "articles-transition-data.txt");
        }

        [Authorize]
        // GET: Articles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Articles.ToListAsync());
        }

        // GET: Articles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles.Include(a => a.Category).FirstOrDefaultAsync(m => m.ArticleId == id);

            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        public async Task<IActionResult> MoveRelated(int? prevId, int? newId)
        {
            if (prevId == null || newId == null)
            {
                return NotFound();
            }
            
            string line = ((float) prevId).ToString("0.0") + ',' + ((float) newId).ToString("0.0");
            System.IO.File.AppendAllText(_articlesTransitionDataPath, line + Environment.NewLine);

            return RedirectToAction(nameof(Details), new {id = newId });
        }

        public async Task<IActionResult> Comments(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comments = await _context.Comments.Where(c => c.ArticleId == id.Value).ToListAsync();

            if (comments == null)
            {
                return NotFound();
            }

            return Json(comments);
        }

        public async Task<IActionResult> Search(int? category, string header, string summery, DateTime? date)
        {
            var result = _context.Articles.AsQueryable();

            if (category != null)
                result = result.Where(x => x.CategoryId == category);
            if (!String.IsNullOrWhiteSpace(header))
                result = result.Where(x => x.Header.Contains(header));
            if (!String.IsNullOrWhiteSpace(summery))
                result = result.Where(x => x.Summery.Contains(summery));
            if (date.HasValue)
                result = result.Where(x => x.DateCreated.Value.Date == date.Value.Date);

            return Json(result);
        }

        public async Task<IActionResult> GetRelatedArticles(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            const int NUM_OF_RELATED_ARTICLES = 3;
            var relatedArticles = new List<Article>();

            try
            {
                int mlRelatedArticle = MachineLearning.GetRelatedArticle(_articlesTransitionDataPath, id.Value);

                if (mlRelatedArticle != id.Value)
                {
                    var article = await _context.Articles.FirstAsync(c => c.ArticleId == mlRelatedArticle);

                    if (article != null)
                    {
                        relatedArticles.Add(article);

                        // Try to find a related article to the related article
                        int mlRelatedToRelatedArticle = MachineLearning.GetRelatedArticle(_articlesTransitionDataPath, mlRelatedArticle);

                        if (mlRelatedToRelatedArticle != mlRelatedArticle && mlRelatedToRelatedArticle != id.Value)
                        {
                            article = await _context.Articles.FirstAsync(c => c.ArticleId == mlRelatedToRelatedArticle);

                            if (article != null)
                            {
                                relatedArticles.Add(article);
                            }
                        }
                    }
                }

            }
            catch (Exception)
            {
                // It's just mean that there is no data yet for this article
            }

            int articlesCount = _context.Articles.Count();
            Random random = new Random();

            // Fill the rest of the related articles with random articles, in order to
            // have the option for diversity (and by that make better predictions in the future)
            while (relatedArticles.Count() < NUM_OF_RELATED_ARTICLES)
            {
                int randomArticleId = random.Next(1, articlesCount);

                if (randomArticleId != id.Value && !relatedArticles.Exists(c => c.ArticleId == randomArticleId))
                {
                    var randomArticle = await _context.Articles.FirstAsync(c => c.ArticleId == randomArticleId);

                    if (randomArticle != null)
                    {
                        relatedArticles.Add(randomArticle);
                    }
                }
            }

            return Json(relatedArticles);
        }

        // GET: Articles/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(_context.Categories, "CategoryId", "Name");
            return View();
        }

        // POST: Articles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Header,Summery,Content,HomeImageUrl,CategoryId,Location,IsShowMap")] Article articleModel)
        {
            if (ModelState.IsValid)
            {
                articleModel.DateCreated = DateTime.Now;
                _context.Add(articleModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(articleModel);
        }

        // GET: Articles/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles.FindAsync(id);
            if (article == null)
            {
                return NotFound();
            }

            ViewBag.Categories = new SelectList(_context.Categories, "CategoryId", "Name");

            return View(article);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("ArticleId,Header,Summery,Content,HomeImageUrl,CategoryId,Location,IsShowMap")] Article article)
        {
            if (id != article.ArticleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Articles.Attach(article);
                    _context.Entry(article).Property(x => x.Content).IsModified = true;
                    _context.Entry(article).Property(x => x.Header).IsModified = true;
                    _context.Entry(article).Property(x => x.Summery).IsModified = true;
                    _context.Entry(article).Property(x => x.HomeImageUrl).IsModified = true;
                    _context.Entry(article).Property(x => x.CategoryId).IsModified = true;
                    _context.Entry(article).Property(x => x.Location).IsModified = true;
                    _context.Entry(article).Property(x => x.IsShowMap).IsModified = true;

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticleExists(article.ArticleId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(article);
        }

        // GET: Articles/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles
                .FirstOrDefaultAsync(m => m.ArticleId == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // POST: Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var article = await _context.Articles.FindAsync(id);
            _context.Articles.Remove(article);
            await _context.SaveChangesAsync();

NewsNow/Views/Articles/Create.cshtml
@model NewsNow.Models.Article

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Article</h4>

<hr />
<div class="row">
    <form asp-action="Create">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ArticleId" />
            <div class="form-group">
                <label asp-for="Header" class="control-label"></label>
                <input asp-for="Header" class="form-control" />
                <span asp-validation-for="Header" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Summery" class="control-label"></label>
                <input asp-for="Summery" class="form-control" />
                <span asp-validation-for="Summery" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                @Html.DropDownList("CategoryId", (SelectList)ViewBag.Categories, "Select Category", new { @class = "form-control" })
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomeImageUrl" class="control-label" title="Home-Image URL"></label>
                <input asp-for="HomeImageUrl" class="form-control" />
                <span asp-validation-for="HomeImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <table>
                    <tr>
                        <th style="vertical-align:top;">
                            <div id="locationContainer" style="width:465px;">
                                <input asp-for="Location" class="form-control" id="locationSearch" autocomplete="off" />
                                <span asp-validation-for="Location" class="text-danger"></span>
                            </div>
                        </th>
                    </tr>
                    <tr>
                        <th>
                            <div id="myMap" style="height:300px;"></div>
                        </th>
                    </tr>
                    <tr>
                        <th>
                            <input type="checkbox" asp-for="IsShowMap" /> Show map in article?
                        </th>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-md-12">
            <div class=" form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" id="MDEditorTextArea"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </form>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


@section Scripts
{
<script type="text/javascript">
    $(document).ready(function () {
        make_markdown_editor($("#MDEditorTextArea")[0], "")
    })

    var map = null;

    function LoadMap() {
        map = new Microsoft.Maps.Map('#myMap', {
            credentials: "AglcOvofpKm1X-WOXDY3_Cr0bxdAbKzUid-4bp7Em3BxbNPK_kT-X8iWI4B1RF0H",
            showMapTypeSelector: false,
            showZoomButtons: false,
            showLocateMeButton: false
        });

        Microsoft.Maps.loadModule('Microsoft.Maps.Search', function () {
            var searchManager = new Microsoft.Maps.Search.SearchManager(map);
            var requestOptions = {
                bounds: map.getBounds(),
                where: decodeHtml(""),
                callback: function (answer, userData) {
                    map.setView({ bounds: answer.results[0].bestView });
                    map.entities.push(new Microsoft.Maps.Pushpin(answer.results[0].location))
                }
            };
            searchManager.geocode(requestOptions);
        });

        Microsoft.Maps.loadModule('Microsoft.Maps.AutoSuggest', function () {
            var options = {
                maxResults: 4,
                map: map
            };
            var manager = new Microsoft.Maps.AutosuggestManager(options);
            manager.attachAutosuggest('#locationSearch', '#locationContainer', selectedSuggestion);
        });
    }

    function selectedSuggestion(suggestionResult) {
        map.entities.clear();
        map.setView({ bounds: suggestionResult.bestView });
        var pushpin = new Microsoft.Maps.Pushpin(suggestionResult.location);
        map.entities.push(pushpin);
        //document.getElementById('printoutPanel').innerHTML =
        //    'Suggestion: ' + suggestionResult.formattedSuggestion +
        //    '<br> Lat: ' + suggestionResult.location.latitude +
        //    '<br> Lon: ' + suggestionResult.location.longitude;
    }
</script>
<script type="text/javascript" src="https://www.bing.com/api/maps/mapcontrol?callback=LoadMap" async defer></script>
}

NewsNow/Views/Articles/Delete.cshtml
@model NewsNow.Models.Article

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Article</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Header)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Header)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ArticleId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

NewsNow/Views/Articles/Details.cshtml
@using Microsoft.AspNetCore.Identity
@using NewsNow.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


@model NewsNow.Models.Article

@{
    ViewData["Title"] = Model.Header;
}

<!-------------------------------HEADER--------------------------------->
<div class="card flex-md-row mb-4 box-shadow h-md-250 text-light bg-dark shadow">
    <div class="card-body d-flex flex-column align-items-start">
        <strong class="d-inline-block mb-2 text-primary">
            <partial name="_CategoryBadge" model="@Model.Category" />
        </strong>
        <h1 class="mb-0">@Model.Header</h1>
        <small>@Html.DisplayFor(model => model.DateCreated)</small>
        <small>@Html.DisplayFor(model => model.Location)</small>
        <br />
        <br />

        <div class="btn-group" role="group" aria-label="...">
            <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button btn btn-sm" data-size="large" data-show-screen-name="false" data-show-count="false">Tweet</a>
            <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

            @if (SignInManager.IsSignedIn(User))
            {
                <a asp-action="Edit" asp-route-id="@Model.ArticleId" class="btn btn-sm btn-outline-secondary">Edit</a>
            }

            <a href="/" class="btn btn-sm btn-outline-secondary">Home</a>
        </div>

    </div>
    <a asp-controller="Articles" asp-action="Details" asp-route-id="@Model.ArticleId" style="background-color:black">
        <img class="card-img-right flex-auto d-none d-md-block" style="width: 400px;" src="@Model.HomeImageUrl" data-holder-rendered="true" />
    </a>
</div>

<div id="adblocker-warning">
    Our website is made possible by displaying online advertisements to our visitors.<br>
    Disable your ad blocker in order to see the content of this article.
</div>

<div class="row">
    <div class="col-md-8">
        <!-------------------------------CONTENT--------------------------------->
        <section>
            <div class="border-bottom p-3">
                @Model.Summery
            </div>
        </section>
        </br>
        <section>
            <div id="ArticleContent" class="border-bottom"></div>
        </section>
        <!-------------------------------COMMENTS--------------------------------->
        <section>
            <div class="col-12">
                <h3>Comments</h3>
                <div class="border-bottom mb-2">
                    <form id="newCommentForm">
                        <div class="form-group form-group-sm">
                            <input type="text" name="Author" class="form-control" placeholder="Who are you?" />
                        </div>
                        <div class="form-group form-group-sm">
                            <textarea name="Content" class="form-control" rows="2" placeholder="And what do you think about this?"></textarea>
                        </div>
                        <div class="form-group form-group-sm">
                            <input type="hidden" name="ArticleId" class="form-control" value="@Model.ArticleId" />
                        </div>
                        <div class="form-group form-group-sm">
                            <button type="button" class="btn btn-success btn-sm mr-2" data-toggle="modal" data-target="#commentModal">Post it!</button>
                            Remember: Keep it clean!
                        </div>
                    </form>
                </div>
                <div class="col-md-12">
                    <small id="commentsCountLabel">
                        Loading comments...
                    </small>
                    <div class="list-group" id="commentsList">
                    </div>
                </div>
                <div id="result">

                </div>
            </div>
        </section>
    </div>
    <div class="col-lg-4">
        <aside>
            <!-------------------------------SIDEBAR--------------------------------->
            <div class="bs-example" data-example-id="default-media">

                @if (Model.IsShowMap)
                {
                    <div class="pb-3 border-bottom">
                        <h3>Location:<span class="badge badge-secondary">@Model.Location</span></h3>
                        <div class="media">
                            <div class=" media-left">
                                <div id="articleMap" class="img-thumbnail" style="width: 350px; height: 300px;"></div>
                            </div>
                        </div>
                    </div>
                }

                <div class="mt-2">
                    <h3>Related...</h3>
                    <div class="related-articles-list" id="relatedArticlesList">
                    </div>
                </div>
            </div>
        </aside>
    </div>
</div>

<!-------------------------------COMMENTS--------------------------------->
<div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="commentModalLabel">Are you sure?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">X</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to post this comment?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="post_comment()">Post comment!</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="errorCommentModal" tabindex="-1" role="dialog" aria-labelledby="errorCommentModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="errorCommentModalLabel">Error</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">X</span>
                </button>
            </div>
            <div class="modal-body">
                Content or author can't be empty!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-------------------------------ADVERTISEMENTS--------------------------------->
<div id="footerAdvWrapper" style="width:100%; position: fixed; bottom: 0; text-align: center;">
    <script type="text/javascript">
        var incomingList = [{
            "t": 1541269796,
            "hash": "bc9yxeefu",
        }, {
            "t": 1541278805,
            "hash": "bzjib88jd",
        }, {
            "t": 1541279046,
            "hash": "bzj5off97",
        }, {
            "t": 1541279342,
            "hash": "bcpib88jd",
        }, {
            "t": 1541279595,
            "hash": "bc50xeefu",
            }];

        var randomAdvertise = Math.round(Math.random() * (incomingList.length - 1));

        var bannersnack_embed = { "hash": incomingList[randomAdvertise].hash, "width": 728, "height": 80, "t": incomingList[randomAdvertise].t, "userId": 38365105, "type": "html5" };
    </script>
    <script type="text/javascript" src="//cdn.bannersnack.com/iframe/embed.js"></script>
</div>



@section Scripts
    {
    <!-------------------------------TEMPLATES--------------------------------->
    <script id="commentTemplate" type="text/x-jQuery-tmpl">
        <div class="media mb-1 border-bottom">
            <div class="media-left">
                <table class="comment-number-container mr-2">
                    <tbody>
                    <td class="align-middle text-center">#${sequence}</td>
                    </tbody>
                </table>
            </div>
            <div class="media-body">
                <small>${author}</small>
                <p>${content}</p>
            </div>
            @if (SignInManager.IsSignedIn(User))
            {
                <button class="btn btn-danger" onclick="_delete_comment(${commentId})">X</button>
            }

        </div>
    </script>

    <script id="relatedArticleTemplate" type="text/x-jQuery-tmpl">
        <div class="card">
            <a asp-controller="Articles" asp-action="Details" asp-route-id="@Model.ArticleId">
                <img class="card-img-top"
                     style="height: 180px; width: 100%; display: block;"
                     src="${homeImageUrl}"
                     data-holder-rendered="true">
            </a>
            <div class="card-body">
                <h5 class="card-title">${header}</h5>
                <a class="btn btn-sm btn-outline-secondary" asp-controller="Articles" asp-action="MoveRelated"
                   href="/Articles/MoveRelated/?prevId=@Model.ArticleId&newId=${articleId}">Read more...</a>
            </div>
        </div>
    </script>

    <script src="~/js/ads.js" type="text/javascript"></script>

    <!-------------------------------SCRIPTS--------------------------------->
    <script async type="text/javascript">
        $(document).ready(function () {
            // Check for adblock
            if (!document.getElementById('check-for-adblocker')) {
                document.getElementById('adblocker-warning').style.display = 'block';
            }
            else {

                $("#ArticleContent").html(markdown_to_html("@Model.Content"));

                load_markdown_tweeter()
            }

            $(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });

            update_related_articles()
            update_comments()
        })

        var update_related_articles = function () {
            var url = "/Articles/GetRelatedArticles/" + @Model.ArticleId;
            $.getJSON(url, function (relatedArticles) {
                relatedArticles.forEach(relatedArticle => {
                    $("#relatedArticleTemplate").tmpl(relatedArticle).appendTo("#relatedArticlesList");
                })
            })
        }

        var post_comment = function () {
            var data = $("#newCommentForm").serializeArray()

            if (data[0].value == "" || data[1].value == "") {
                $('#errorCommentModal').modal('show');
            }

            new_comment(data[0].value, data[1].value, data[2].value).then(function () {
                update_comments()
            });

            console.log(data)
        }

        var _delete_comment = function (id) {
            delete_comment(id).then(function () {
                update_comments();
            })
        }

        var update_comments = function () {
            get_comments(@Model.ArticleId).then(function (comments) {
                $("#commentsList").html("");
                comments.forEach(comment => {
                    $("#commentTemplate").tmpl(comment).appendTo("#commentsList");
                    console.log(comment)
                })
                $("#commentsCountLabel").html(comments.length + " Comments")
            })
        }

    </script>

    @if (Model.IsShowMap)
    {
        <script type="text/javascript">
            var map = null;

            function LoadMap() {
                map = new Microsoft.Maps.Map('#articleMap', {
                    credentials: "AglcOvofpKm1X-WOXDY3_Cr0bxdAbKzUid-4bp7Em3BxbNPK_kT-X8iWI4B1RF0H",
                    showMapTypeSelector: false,
                    showZoomButtons: false,
                    showLocateMeButton: false
                });

                Microsoft.Maps.loadModule('Microsoft.Maps.Search', function () {
                    var searchManager = new Microsoft.Maps.Search.SearchManager(map);
                    var requestOptions = {
                        bounds: map.getBounds(),
                        where: decodeHtml("@Model.Location"),
                        callback: function (answer, userData) {
                            map.setView({ bounds: answer.results[0].bestView });
                            map.entities.push(new Microsoft.Maps.Pushpin(answer.results[0].location))
                        }
                    };
                    searchManager.geocode(requestOptions);
                });
            }

        </script>
        <script type="text/javascript" src="https://www.bing.com/api/maps/mapcontrol?callback=LoadMap" async defer></script>
    }
}

NewsNow/Views/Articles/Index.cshtml
@model IEnumerable<NewsNow.Models.Article>

@{
    ViewData["Title"] = "Browse";
    ViewData["Tab"] = "Browse";
}

<h2>Browse all articles</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Header)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArticleId)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Header)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ArticleId)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ArticleId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ArticleId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ArticleId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>